# Generated by Django 5.1.4 on 2025-01-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_oil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil',
            name='type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1),
        ),
    ]
