# Generated by Django 5.1.4 on 2025-01-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_oil_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='oil',
            name='type',
            field=models.CharField(choices=[('M', 'Mumtaz'), ('J', 'Jayed'), ('S', 'Super')], max_length=1),
        ),
        migrations.AddField(
            model_name='car',
            name='medals',
            field=models.ManyToManyField(to='main_app.medal'),
        ),
    ]
